name: SpringPads
version: ${version}
main: com.github.dwesolowski.springpads.SpringPads
api-version: 1.13

commands:
  springpads:
    usage: |
      /<command> create : Places a pad at current location.
      /<command> reload : Reloads the configuration file.
    description: "/<springpads> <command>"
    permission: springpads.admin

permissions:
  springpads.admin:
    description: "Gives access to all SpringPads commands."
    default: op